### ISSUE TITLE
Letztes Datenupdate 30.12.2020

### ISSUE THREAD

**Issue by gusowski1** [mh-/diagnosis-keys#17]
Currently the stats aren't updated anymore.
Is there an issue within your part - or is it an upstream issue?

**Comment by mh-** [comment]
Which stats?

**Comment by gusowski1** [comment]
https://micb25.github.io/dka/ this graphs

**Comment by mh-** [comment]
Ok, but sorry, I don’t know - you might want to check here: https://github.com/micb25/dka/issues
