### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Tho-Mat** [mh-/diagnosis-keys#3]
@mh- 
May be you could help me.

On 01.07.2020 17:00 there was a key-sequence 

```
| risk| date | keys| 
| 7 | 18.06. | 10/10 | 
| 8 | 19.06. | 10/10 | 
| 7 | 20.06. | 10/10 | 
| 5 | 21.06. | 10/10 | 
| 3 | 22.06. | 10/10 | 
| 2 | 24.06. | 10/10 | 
| 1 | 25.06. | 10/10 | 
| 1 | 28.06. | 10/10 | 
| 1 | 29.06. | 10/10 | 
| 1 | 30.06. | 10/10 |

```
published by one user.
But I'm not able to find out the code in the corona-warn-app, that causes the remove of the | 6 | 17.06.|10/10| key.
I believe it has something to do with the age of 17.06. It is just one day to old.
I know the other bugs, (wrong order, wrong risk values), but that do not explain the removal.

**Comment by mh-** [comment]
@Tho-Mat in that case the server has removed the key because of the age.

**Comment by Tho-Mat** [comment]
Thanks for quick answer.
