### ISSUE TITLE
proto file has changed yesterday

### ISSUE THREAD

**Issue by pdehaye** [mh-/diagnosis-keys#4]
The TEK file format has changed:

https://developers.google.com/android/exposure-notifications/exposure-key-file-format

**Comment by mh-** [comment]
Thanks, do you have indications that the data provided by cwa-server has changed as well, or will change in the future?

**Comment by pdehaye** [comment]
None, but one part was marked as `deprecated = True`, on the risk level, and that is important for CWA.  

I am using your software to analyze the keys coming from multiple countries (lv, at, dk, de, it, ch, pl), so I am keen for it to remain up to date. 

I would also be keen to see if we could replicate your dashboards for different countries, but at the moment the main obstacle is the upload logic which differs from country to country and is very obscure.

**Comment by mh-** [comment]
The new version is called v1.5 by Google, and discussed here: https://github.com/google/exposure-notifications-server/issues/663, see also https://github.com/google/exposure-notifications-server/issues/662

Note that the spec states that the header must still "be exactly “EK Export v1”". I wonder why.

**Comment by ndegendogo** [comment]
> the spec states that the header must still "be exactly “EK Export v1”". I wonder why

They are using the header in case of future breaking ( = not backwards compatible) changes

> The export file format is designed to ensure forward and backward compatibility [...] A breaking change to the format (which is considered extremely unlikely) will be signalled by a change to the "EK Export v1" header.

**Comment by mh-** [comment]
Yes, well, from my perspective, the changes have been _breaking_ already.
